### ISSUE TITLE
metalsmith or assemble-core ;-)

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble-core#2]
Hi,

I guess you wanted to show how a plugin for assemble-core and not for metalsmith can be written, right? ;-)

https://github.com/assemble/assemble-core/tree/master/examples/drafts-plugin

Regards
Stefan

**Comment by jonschlinkert** [comment]
https://github.com/assemble/assemble-core/tree/master/examples#examples

Did you see the readme? :) we like metalsmith, it's a great build system.

**Comment by jonschlinkert** [comment]
oh I see - the link you point to, it's not technically a typo, we just brought in the metalsmith examples like I mentioned in the readme, and didn't change those since I was trying to keep it as close to it was as possible. I didn't think about that but it's obviously confusing the way it is. I'll change those with a note. 

thanks!

**Comment by stefanwalther** [comment]
;-)

**Comment by jonschlinkert** [comment]
closing based on age
